# Generated by Django 5.2.4 on 2026-01-04 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_user_laundrymart_logo_laundrymartstore_and_more'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='review',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='laundrymart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='received_reviews', to='accounts.laundrymartstore'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='review',
            name='vendor',
        ),
    ]
