# Generated by Django 5.2.4 on 2026-01-08 04:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_review_unique_together_review_comment_and_more'),
        ('payment', '0007_order_customer_note'),
        ('uber', '0011_deliveryquote_customer_note'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery_quote', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_filed_report', to='uber.deliveryquote')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_filed_report', to='payment.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_filed_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderReportImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='order_customer_report_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='customer.orderreport')),
            ],
        ),
    ]
