# Generated by Django 5.2.4 on 2025-12-28 05:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('pickup_address', models.JSONField()),
                ('dropoff_address', models.JSONField()),
                ('uber_pickup_quote_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('uber_pickup_delivery_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('uber_return_quote_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('uber_return_delivery_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=100, null=True)),
                ('stripe_default_pm_id', models.CharField(blank=True, max_length=100, null=True)),
                ('weight_in_pounds', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('service_charge_cents', models.PositiveIntegerField(blank=True, null=True)),
                ('delivery_fee_cents', models.PositiveIntegerField(blank=True, null=True)),
                ('final_total_cents', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending_setup', 'Pending Card Setup'), ('card_saved', 'Card Saved – Awaiting Pickup'), ('picked_up', 'Picked Up'), ('weighed', 'Weighed & Priced'), ('charged', 'Charged'), ('return_scheduled', 'Return Delivery Scheduled'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='pending_setup', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_payment_intent_id', models.CharField(max_length=100, unique=True)),
                ('amount_cents', models.PositiveIntegerField()),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='payment.order')),
            ],
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='payment_ord_status_4b9fa9_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user'], name='payment_ord_user_id_14d54e_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['stripe_customer_id'], name='payment_ord_stripe__310c96_idx'),
        ),
    ]
