# Generated by Django 5.2.4 on 2025-12-28 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_order_service_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='dropoff_address',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='pickup_address',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
