# Generated by Django 5.2.4 on 2026-01-04 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_order_dropoff_latitude_order_dropoff_longitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending_setup', 'Pending Card Setup'), ('processing', 'Processing – Creating Delivery'), ('card_saved', 'Card Saved – Awaiting Pickup'), ('picked_up', 'Picked Up'), ('weighed', 'Weighed & Priced'), ('charged', 'Charged'), ('return_scheduled', 'Return Delivery Scheduled'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='pending_setup', max_length=30),
        ),
        migrations.CreateModel(
            name='PendingStripeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('stripe_session_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_stripe_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
