# Generated by Django 5.2.4 on 2026-01-05 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_laundrymartstore_auto_accept_orders_and_more'),
        ('payment', '0005_alter_order_status_pendingstripeorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='service_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_orders', to='accounts.laundrymartstore'),
        ),
    ]
