# Generated by Django 5.2.4 on 2026-01-08 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_order_customer_note'),
        ('uber', '0011_deliveryquote_customer_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='parent_deivery',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uber_parent_deivery', to='uber.delivery'),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_deivery',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uber_pickup_deivery', to='uber.delivery'),
        ),
        migrations.AddField(
            model_name='order',
            name='return_delivery',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uber_return_delivery', to='uber.delivery'),
        ),
    ]
