# Generated by Django 5.2.4 on 2025-12-23 04:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_style', models.CharField(blank=True, max_length=50, null=True)),
                ('quote_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('pickup_address', models.TextField(blank=True, null=True)),
                ('dropoff_address', models.TextField(blank=True, null=True)),
                ('pickup_latitude', models.FloatField(blank=True, null=True)),
                ('pickup_longitude', models.FloatField(blank=True, null=True)),
                ('dropoff_latitude', models.FloatField(blank=True, null=True)),
                ('pickup_phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('dropoff_phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('manifest_total_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('external_store_id', models.CharField(blank=True, null=True)),
                ('fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(blank=True, max_length=20, null=True)),
                ('currency_type', models.CharField(blank=True, max_length=20, null=True)),
                ('dropoff_eta', models.DateTimeField(blank=True, null=True)),
                ('duration', models.PositiveIntegerField(blank=True, help_text='Estimated total duration in minutes', null=True)),
                ('pickup_duration', models.PositiveIntegerField(blank=True, help_text='Estimated pickup duration in minutes', null=True)),
                ('dropoff_deadline', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('expires', models.DateTimeField(blank=True, null=True)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_quotes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Uber Direct Delivery Quote',
                'verbose_name_plural': 'Uber Direct Delivery Quotes',
                'ordering': ['-saved_at'],
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_uid', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('batch_id', models.CharField(blank=True, max_length=255, null=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('pickup_name', models.CharField(blank=True, max_length=255, null=True)),
                ('pickup_address', models.TextField(blank=True, null=True)),
                ('pickup_phone_number', models.CharField(blank=True, max_length=30, null=True)),
                ('pickup_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('pickup_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('pickup_notes', models.TextField(blank=True, null=True)),
                ('pickup_ready', models.DateTimeField(blank=True, null=True)),
                ('pickup_business_name', models.CharField(blank=True, max_length=255, null=True)),
                ('dropoff_name', models.CharField(blank=True, max_length=255, null=True)),
                ('dropoff_address', models.TextField(blank=True, null=True)),
                ('dropoff_phone_number', models.CharField(blank=True, max_length=30, null=True)),
                ('dropoff_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('dropoff_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('dropoff_notes', models.TextField(blank=True, null=True)),
                ('dropoff_seller_notes', models.TextField(blank=True, null=True)),
                ('dropoff_business_name', models.CharField(blank=True, max_length=255, null=True)),
                ('external_store_id', models.CharField(blank=True, max_length=100, null=True)),
                ('external_id', models.CharField(blank=True, max_length=100, null=True)),
                ('deliverable_action', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='usd', max_length=3)),
                ('tracking_url', models.URLField(blank=True, null=True)),
                ('dropoff_eta', models.DateTimeField(blank=True, null=True)),
                ('dropoff_deadline', models.DateTimeField(blank=True, null=True)),
                ('completion_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('completion_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('courier_name', models.CharField(blank=True, max_length=255, null=True)),
                ('courier_tip', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('courier_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('courier_vehicle_type', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at_uber', models.DateTimeField(blank=True, null=True)),
                ('updated_at_uber', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to=settings.AUTH_USER_MODEL)),
                ('quote', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='uber.deliveryquote')),
            ],
            options={
                'verbose_name': 'Uber Direct Delivery',
                'verbose_name_plural': 'Uber Direct Deliveries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ManifestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=255)),
                ('dimensions', models.JSONField(blank=True, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('vat_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uber.delivery')),
            ],
        ),
    ]
