# Generated by Django 5.2.4 on 2025-12-24 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uber', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryquote',
            name='delivery_style',
        ),
        migrations.AddField(
            model_name='delivery',
            name='parent_delivery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_deliveries', to='uber.delivery'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='quote_uid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='total_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='deliveryquote',
            name='service_type',
            field=models.CharField(blank=True, choices=[('drop_off', 'Drop off'), ('pickup', 'Pick up'), ('full_service', 'Full service')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='manifestitem',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='deliverable_action',
            field=models.CharField(blank=True, choices=[('deliverable_action_meet_at_door', 'deliverable_action_meet_at_door'), ('deliverable_action_leave_at_door', 'deliverable_action_leave_at_door')], default='deliverable_action_meet_at_door', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='manifestitem',
            name='name',
            field=models.CharField(default='Bag', max_length=255),
        ),
        migrations.AlterField(
            model_name='manifestitem',
            name='size',
            field=models.CharField(choices=[('small', 'Small'), ('big', 'Big'), ('medium', 'Medium')], max_length=255),
        ),
    ]
