# Generated by Django 5.2.4 on 2025-12-24 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uber', '0002_remove_deliveryquote_delivery_style_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryquote',
            name='dropoff_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
