# Generated by Django 5.2.4 on 2025-12-27 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uber', '0003_deliveryquote_dropoff_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='external_store_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='quote_uid',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryquote',
            name='external_store_id',
            field=models.CharField(blank=True, db_index=True, null=True),
        ),
    ]
