# Generated by Django 5.2.4 on 2025-12-27 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uber', '0004_alter_delivery_external_store_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='uber_raw_response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryquote',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], max_length=50, null=True),
        ),
    ]
