# Generated by Django 5.2.4 on 2025-12-27 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uber', '0005_delivery_uber_raw_response_deliveryquote_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryquote',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=50, null=True),
        ),
    ]
