# Generated by Django 5.2.4 on 2026-01-04 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uber', '0006_alter_deliveryquote_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryquote',
            name='scheduled_pickup_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
