# Generated by Django 5.2.4 on 2026-01-05 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uber', '0007_deliveryquote_scheduled_pickup_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('pickup_true', 'Pickup True'), ('pickup_false', 'Pickup False'), ('pickup_complete', 'Pickup Complete'), ('dropoff_true', 'Dropoff True'), ('dropoff_false', 'Dropoff False'), ('delivered', 'Delivered'), ('canceled', 'Canceled'), ('returned', 'Returned')], max_length=100, null=True),
        ),
    ]
