# Generated by Django 5.2.4 on 2026-01-06 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_alter_order_service_provider'),
        ('uber', '0008_alter_delivery_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifestitem',
            name='stripe_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manifest_items', to='payment.order'),
        ),
        migrations.AlterField(
            model_name='manifestitem',
            name='delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manifest_items', to='uber.delivery'),
        ),
    ]
