# Generated by Django 5.2.4 on 2026-01-06 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uber', '0009_manifestitem_stripe_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifestitem',
            name='delivery_quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manifest_items', to='uber.deliveryquote'),
        ),
    ]
