# Generated by Django 5.2.4 on 2026-01-07 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uber', '0010_manifestitem_delivery_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryquote',
            name='customer_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
