# Generated by Django 5.2.4 on 2026-01-10 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uber', '0012_rename_scheduled_pickup_time_deliveryquote_pickup_ready_dt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryquote',
            name='currency',
            field=models.CharField(blank=True, default='usd', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryquote',
            name='currency_type',
            field=models.CharField(blank=True, default='USD', max_length=20, null=True),
        ),
    ]
