# Generated by Django 5.2.4 on 2026-01-10 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uber', '0013_alter_deliveryquote_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryquote',
            name='status',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='card_authorization', max_length=50, null=True),
        ),
    ]
