# Generated by Django 5.2.4 on 2026-01-10 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uber', '0014_alter_deliveryquote_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryquote',
            name='payment_method_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
