# Generated by Django 5.2.4 on 2025-12-08 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_lat_user_lng'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='secondary_lat',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='secondary_lng',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='secondary_location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
