# Generated by Django 5.2.4 on 2025-12-08 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_daily_capacity_limit_user_laundrymart_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='operating_hours_end_saturday',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='operating_hours_start_saturday',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
