# Generated by Django 5.2.4 on 2025-12-08 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_is_closed_friday_user_is_closed_monday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auto_accept_orders',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='preference',
            field=models.CharField(blank=True, choices=[('Auto-assign another LaundryMart (fastest)', 'Auto-assign another LaundryMart (fastest)'), ('Ask me to choose (I’ll decide each time)', 'Ask me to choose (I’ll decide each time)')], default='Auto-assign another LaundryMart (fastest)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='push_and_email_alerts',
            field=models.BooleanField(default=True),
        ),
    ]
