# Generated by Django 5.2.4 on 2025-12-21 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_auto_accept_orders_user_preference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='vendor_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
