# Generated by Django 5.2.4 on 2025-12-24 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_user_lat_alter_user_lng_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='store_id',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
