# Generated by Django 5.2.4 on 2026-01-04 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_user_stripe_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='laundrymart_logo',
            field=models.ImageField(blank=True, null=True, upload_to='laundrymart_logos/'),
        ),
        migrations.CreateModel(
            name='LaundrymartStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laundrymart_name', models.CharField(max_length=255)),
                ('store_id', models.UUIDField(blank=True, null=True, unique=True)),
                ('laundrymart_logo', models.ImageField(blank=True, null=True, upload_to='laundrymart_logo')),
                ('image', models.ImageField(blank=True, null=True, upload_to='laundrymart_image')),
                ('price_per_pound', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('service_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('vendor_description', models.TextField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('secondary_location', models.TextField(blank=True, null=True)),
                ('secondary_lat', models.FloatField(blank=True, null=True)),
                ('secondary_lng', models.FloatField(blank=True, null=True)),
                ('minimum_order_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('daily_capacity_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('turnaround_time_minimum_sunday', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('turnaround_time_maximum_sunday', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('turnaround_time_minimum_monday', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('turnaround_time_maximum_monday', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('turnaround_time_minimum_tuesday', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('turnaround_time_maximum_tuesday', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('turnaround_time_minimum_wednesday', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('turnaround_time_maximum_wednesday', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('turnaround_time_minimum_thursday', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('turnaround_time_maximum_thursday', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('turnaround_time_minimum_friday', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('turnaround_time_maximum_friday', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('turnaround_time_minimum_saturday', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('turnaround_time_maximum_saturday', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('operating_hours_start_sunday', models.TimeField(blank=True, null=True)),
                ('operating_hours_end_sunday', models.TimeField(blank=True, null=True)),
                ('is_closed_sunday', models.BooleanField(default=False)),
                ('operating_hours_start_monday', models.TimeField(blank=True, null=True)),
                ('operating_hours_end_monday', models.TimeField(blank=True, null=True)),
                ('is_closed_monday', models.BooleanField(default=False)),
                ('operating_hours_start_tuesday', models.TimeField(blank=True, null=True)),
                ('operating_hours_end_tuesday', models.TimeField(blank=True, null=True)),
                ('is_closed_tuesday', models.BooleanField(default=False)),
                ('operating_hours_start_wednesday', models.TimeField(blank=True, null=True)),
                ('operating_hours_end_wednesday', models.TimeField(blank=True, null=True)),
                ('is_closed_wednesday', models.BooleanField(default=False)),
                ('operating_hours_start_thursday', models.TimeField(blank=True, null=True)),
                ('operating_hours_end_thursday', models.TimeField(blank=True, null=True)),
                ('is_closed_thursday', models.BooleanField(default=False)),
                ('operating_hours_start_friday', models.TimeField(blank=True, null=True)),
                ('operating_hours_end_friday', models.TimeField(blank=True, null=True)),
                ('is_closed_friday', models.BooleanField(default=False)),
                ('operating_hours_start_saturday', models.TimeField(blank=True, null=True)),
                ('operating_hours_end_saturday', models.TimeField(blank=True, null=True)),
                ('is_closed_saturday', models.BooleanField(default=False)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_stores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'LaundryMart Store',
                'verbose_name_plural': 'LaundryMart Stores',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='laundrymart_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='accounts.laundrymartstore'),
        ),
        migrations.AlterField(
            model_name='service',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_services', to='accounts.laundrymartstore'),
        ),
    ]
