# Generated by Django 5.2.4 on 2026-01-04 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_user_laundrymart_logo_laundrymartstore_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laundrymartstore',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
