# Generated by Django 5.2.4 on 2026-01-04 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_remove_user_daily_capacity_limit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='laundrymart_logo',
        ),
    ]
