# Generated by Django 5.2.4 on 2026-01-04 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_remove_user_laundrymart_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='laundrymartstore',
            name='auto_accept_orders',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='laundrymartstore',
            name='push_and_email_alerts',
            field=models.BooleanField(default=True),
        ),
    ]
