# Generated by Django 5.2.4 on 2026-01-06 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_laundrymartstore_auto_accept_orders_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='price_per_pound',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
