# Generated by Django 5.2.4 on 2026-01-10 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_service_price_per_pound'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='approved_by_admin',
            field=models.BooleanField(default=False),
        ),
    ]
