# Generated by Django 5.2.4 on 2026-01-06 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_service_price_per_pound'),
        ('messaging', '0002_room_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Important', 'Important'), ('Promotional', 'Promotional')], default='Normal', max_length=255),
        ),
        migrations.CreateModel(
            name='VendorNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Normal', 'Normal'), ('Important', 'Important'), ('Promotional', 'Promotional')], default='Normal', max_length=255)),
                ('text', models.TextField(max_length=1000)),
                ('target_url', models.CharField(blank=True, max_length=255, null=True)),
                ('additional_info', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_read', models.BooleanField(default=False)),
                ('seen', models.BooleanField(default=False)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_notifications', to='accounts.laundrymartstore')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
